2021-0513-01)

특정 부서번호를 입력하여 해당부서의 부서장 이름과 부서의 평균급여를 출력하는
PROCEDURE를 작성하시오
부서장 이름과 평균급여는 OUT매개변수로 처리

CREATE OR REPLACE PROCEDURE PROC_EMP02(
  P_DEPT_ID IN  departments.department_id%TYPE,
  P_MNAME OUT EMPLOYEES.EMP_NAME%TYPE,
  P_ASAL  OUT NUMBER)
Is
BEGIN
-- 부서장 이름 검색
  SELECT A.EMP_NAME    
    INTO P_MNAME
    FROM EMPLOYEES A, DEPARTMENTS B
   WHERE P_DEPT_ID = B.DEPARTMENT_ID
     AND A.EMPLOYEE_ID = B.MANAGER_ID;
 
 --부서의 평균 급여
  SELECT round(AVG(SALARY))
    INTO P_ASAL
    FROM EMPLOYEES
   WHERE DEPARTMENT_ID = P_DEPT_ID;
END;


DECLARE
 V_NAME EMPLOYEES.EMP_NAME%TYPE;
 V_SAL NUMBER:=0;
BEGIN
 PROC_EMP02(90,V_NAME,V_SAL);
 DBMS_OUTPUT.PUT_LINE('부서장 명 : '||V_NAME);
 DBMS_OUTPUT.PUT_LINE('부서평균 급여 :'||V_SAL);
END;


CREATE OR REPLACE PROCEDURE PROC_MEM02(
 P_MEM_ID   IN  MEMBER.MEM_ID%TYPE,
 P_MEM_NAME OUT MEMBER.MEM_NAME%TYPE,
 P_MEM_JOB  OUT MEMBER.MEM_JOB%TYPE,
 P_MEM_ADD  OUT CHAR)
IS
BEGIN
    SELECT  MEM_NAME,MEM_JOB,MEM_ADD1||' '||MEM_ADD2 
      INTO  P_MEM_NAME,P_MEM_JOB,P_MEM_ADD
      FROM  MEMBER
     WHERE  MEM_ID = P_MEM_ID;
END;


DECLARE
    V_NAME MEMBER.MEM_ID%TYPE;
    V_JOB  MEMBER.MEM_JOB%TYPE;
    V_ADD  VARCHAR2(200):='';
BEGIN
    PROC_MEM02('001',V_NAME,V_JOB,V_ADD);
    DBMS_OUTPUT.PUT_LINE('회원명 : '||V_NAME);
    DBMS_OUTPUT.PUT_LINE('직업 : '||V_JOB);
    DBMS_OUTPUT.PUT_LINE('주소 : '||V_ADD);
END;


ACCEPT P_MID PROMT '회원코드 (영문자+숫자) : '
DECLARE
    V_MID  member.mem_id%type:='&P_MID';
    V_NAME MEMBER.MEM_NAME%TYPE;
    V_JOB  MEMBER.MEM_JOB%TYPE;
    V_ADD  VARCHAR2(200):='';
BEGIN
    PROC_MEM02(V_MID,V_NAME,V_JOB,V_ADD);
    DBMS_OUTPUT.PUT_LINE('회원명 : '||V_NAME);
    DBMS_OUTPUT.PUT_LINE('직업 : '||V_JOB);
    DBMS_OUTPUT.PUT_LINE('주소 : '||V_ADD);
    exception
    when no_data_found then null;
END;


국가코드(countries)에서 국가코드를 입력받아 국가명과 대륙이름을 반환하는 프로시져를 작성하시오

CREATE OR REPLACE PROCEDURE PROC_COUNTRIES(
    P_CID IN   COUNTRIES.COUNTRY_ID%TYPE,
    P_CNAME OUT COUNTRIES.COUNTRY_NAME%TYPE,
    P_RNAME OUT REGIONS.REGION_NAME%TYPE)
IS
BEGIN
    SELECT A.COUNTRY_NAME,B.REGION_NAME
      INTO P_CNAME,P_RNAME
      FROM COUNTRIES A, REGIONS B
     WHERE A.REGION_ID = B.REGION_ID
       AND A.COUNTRY_ID = P_CID;
END;


DECLARE
    V_CNAME COUNTRIES.COUNTRY_NAME%TYPE;
    V_RNAME REGIONS.REGION_NAME%TYPE;
BEGIN
    proc_countries('NG',V_CNAME,V_RNAME);
    DBMS_OUTPUT.PUT_LINE('국가명 : '||V_CNAME);
    DBMS_OUTPUT.PUT_LINE('대륙명 : '||V_RNAME);
END;