2021-0507-01 오라클 객체

select * from remain;

CREATE OR REPLACE VIEW V_MEM01
AS 
    SELECT  MEM_ID,
            MEM_NAME,
            MEM_JOB,
            MEM_MILEAGE
    FROM    MEMBER
    WHERE   MEM_MILEAGE >= 3000
    ;
SELECT * FROM V_MEM01;

UPDATE V_MEM01
   SET MEM_MILEAGE = 9900
 WHERE MEM_ID = LOWER('K001');
 
SELECT MEM_NAME, MEM_MILEAGE
  FROM MEMBER
 WHERE MEM_ID = LOWER('K001');
 
 
 
뷰 V_MEM01에서 오철희 회원의 마일리지를 2700으로 변경하여라.
UPDATE V_MEM01
  SET  MEM_MILEAGE = 2700
 WHERE MEM_MANE = '오철희';
-- View는 마일리지가 3000이상인 사람들로 구성되어 있기 때문에
-- 오철희가 존재하지 않음

UPDATE MEMBER
   SET MEM_MILEAGE = 2700
 WHERE MEM_NAME = '오철희';
 
 CREATE OR REPLACE VIEW V_MEM01
AS 
    SELECT  MEM_ID,
            MEM_NAME,
            MEM_JOB,
            MEM_MILEAGE
    FROM    MEMBER
    WHERE   MEM_MILEAGE >= 3000
    with read only
    ;
SELECT * FROM V_MEM01;

UPDATE member
  SET  MEM_MILEAGE = 8500
 WHERE MEM_NAME ;
 
CREATE SEQUENCE SEQ_CART
START WITH 100;
SELECT SEQ_CART.NEXTVAL FROM DUAL;
SELECT SEQ_CART.CURRVAL FROM DUAL;



CREATE SEQUENCE SEQ_LPROD
  START WITH 11;
INSERT INTO LPROD
VALUES ( SEQ_LPROD.NEXTVAL,'P501','농산물');
INSERT INTO LPROD
VALUES ( SEQ_LPROD.NEXTVAL,'P502','수산물');
INSERT INTO LPROD
VALUES ( SEQ_LPROD.NEXTVAL,'P503','임산물');
SELECT * FROM LPROD;

