2021-0422-01

SELECT  SYSDATE+10,
        SYSDATE-10,
        TRUNC(SYSDATE)-TO_DATE('20200422') --시간은 DEFAULT로 00시00분으로 세팅
  FROM  DUAL;
  
SELECT MOD(TRUNC(SYSDATE)-TO_DATE('00010101'),7)-1
FROM DUAL;
  
SELECT ADD_MONTHS(SYSDATE, 14) FROM DUAL;
--회원 관리, 유효기간등에 이용

SELECT  EMPLOYEE_ID AS 사원번호, 
        EMP_NAME AS 사원명, 
        DEPARTMENT_ID AS 부서코드, 
        HIRE_DATE AS 입사일, 
        ADD_MONTHS(HIRE_DATE,3) AS 발령일
  FROM  HR.EMPLOYEES
ORDER BY 1;


SELECT  SYSDATE,NEXT_DAY(SYSDATE,'목') FROM DUAL;
SELECT  SYSDATE,NEXT_DAY(SYSDATE,'목요일') FROM DUAL;

SELECT LAST_DAY('20280201') FROM DUAL;


SELECT  MEM_ID AS 회원번호, 
        MEM_NAME AS 회원명, 
        MEM_BIR AS 생년월일
  FROM  MEMBER
 WHERE  EXTRACT(MONTH FROM MEM_BIR) = EXTRACT(MONTH FROM SYSDATE);
 
 
SELECT  EMPLOYEE_ID AS 사원번호,
        EMP_NAME AS 사원명,
        HIRE_DATE AS 입사일,
        EXTRACT(YEAR FROM SYSDATE)-EXTRACT(YEAR FROM HIRE_DATE) 
        AS 근속년수, 
        ROUND(SALARY*((EXTRACT(YEAR FROM SYSDATE)
                    -EXTRACT(YEAR FROM HIRE_DATE))/100),-2)
        AS 보너스
  FROM  EMPLOYEES
 WHERE  (EXTRACT(YEAR FROM SYSDATE)-EXTRACT(YEAR FROM HIRE_DATE)) >= 15
 ORDER BY 1
;