2021-0510-01)

CREATE OR REPLACE SYNONYM EMP FOR HR.EMPLYOEES;
ROLLBACK;
COMMIT;
SELECT * FROM EMP;

CREATE OR REPLACE SYNONYM CVIEW FOR V_CART;

SELECT * FROM CVIEW;

SELECT * FROM EMP;

CREATE OR REPLACE SYNONYM DD FOR SYsS.DUAL;
SELECT SYSDATE FROM DD;

DROP SYNONYM CVIEW;
COMMIT;

CREATE INDEX IDX_MEM
    ON MEMBER(MEM_REGNO1,MEM_REGNO2);
SELECT  MEM_ID, MEM_NAME, MEM_ADD1||' '||MEM_ADD2
  FROM  MEMBER
 WHERE  MEM_REGNO1 = '751019'
   AND  MEM_REGNO2 = '2448920';
-- 인덱스인 컬럼을 WHERE절에 전부 기술해야 한다.
   

CREATE INDEX IDX_PROD
    ON PROD(SUBSTR(PROD_ID,2));
SELECT  *
  FROM  PROD
 WHERE  SUBSTR(PROD_ID,2) = '201000002';  
-- FUNCTION - BASED NORMAL타입의 인덱스는 WHERE절에 그 함수를 전보 기술한다.